### ISSUE TITLE
정오표 추가 요청합니다.

### ISSUE THREAD

**Issue by routee90** [lovedlim/bigdata_analyst_cert#10]
p527 상단 [문제2] 선형회귀 하단
 - data: system.csv → system_cpu.csv 로 변경 요청

p523 하단 [문제1] 로지스틱 회귀
 - 위와 같이 data를 어떤 파일을 사용하라는 명시가 안되어 있음.

**Comment by routee90** [comment]
추가적으로
p532 [문제3]에서 코드 상단에는 data를 chem.csv를 사용하라고 되어있는데, 코드상에서는 air_quality.csv를 사옹하고 있습니다. 수정바랍니다.

**Comment by lovedlim** [comment]
꼼꼼한 제보 너무 감사드립니다. 🙇🏻‍♂️ 정오표에 반영했어요!!
이번 시험 합격 응원할게요!! 💪💪💪
