### ISSUE TITLE
정오표 추가해주세요~

### ISSUE THREAD

**Issue by routee90** [lovedlim/bigdata_analyst_cert#11]
p493 코드 상의 데이터 파일명과 위에서 주어진 데이터 파일명 불일치
p539 작업형 제3유형 문제 1에 종속변수가 어떤 컬럼명인지 제시되지 않았음
p543 문제 2에 사용하라고 제시된 데이터 파일명과 코드 상의 데이터 파일명 불일치

확인 부탁드립니다.

**Comment by lovedlim** [comment]
routee90님 항상 감사드립니다. 
꼼꼼히 봐주시고 또 귀찮으실텐데 피드백까지 주셔서 감사해요!!
덕분에 많은 부분 수정할 수 있었네요 진심으로 감사드립니다. 💪💪💪
내일 시험 잘보고 오시길 응원하겠습니다!
