### ISSUE TITLE
정오표 추가해야 할 내용 어디에 올려야 할지 몰라서 여기 올립니다.

### ISSUE THREAD

**Issue by routee90** [lovedlim/bigdata_analyst_cert#3]
안녕하세요, 작업형3 공부하면서 이상하거나 논리적으로 맞지 않는 부분 2개를 발견하여 올립니다.

1. p344 상단 귀무가설 부분에 아메리카노 한 잔의 원두의 중앙값 -> 팝콘 라지 사이즈의 평균 무게
2. p348 문제에서 단, 성과 데이터 차이는 정규 분포를 따른다고 가정한다 -> 해당 부분 제거 필요(내용을 읽어보면 정규성을 만족하지 않으므로 Wilcoxon 검정을 이용하여 검정하고 있음)

추가적으로 읽다가 내용적으로 맞지 않는 부분은 어디에 올려드리면 좋을지 제시해주시는 게 좋겠네요.
초본이라 그런지 상당히 오타나 이상한 내용이 좀 많은 것 같네요.

**Comment by lovedlim** [comment]
gpt 자동 답변을 달아놨더니 이런 단점이 있군요 하하 (아마 제 글에도 답글이 달릴 것 같아요. 신경쓰지 마세요!)
제보주신 내용 너무 감사합니다. 😊 곧 정오표 수정할게요! 학습하면서 이상한 부분이 보인다면 이렇게 이슈에 올려주시면 반영하도록 하겠습니다. 그리고 합격 응원하겠습니다!
