### ISSUE TITLE
빅데이터 분석기사 책 내용상 애매하게 적혀있는 부분 관련하여 여쭙습니다.

### ISSUE THREAD

**Issue by routee90** [lovedlim/bigdata_analyst_cert#4]
안녕하세요,

p378~p379 부분에서 어떤 가설에 대한 p-value 인지 책의 내용을 보충해주셨으면 좋겠습니다. 이것만 보고 판단하기엔 너무 애매하네요.

제가 알고 있는 지식으로는 상관계수의 절대값이 0.6 이상일 경우에는 서로 상관관계가 있다고 알고 있고, 그걸 참고하여 판단하는 것으로 알고 있는데, 여기서 나타나는 p값은 '키와 몸무게는 서로 상관관계이다 or 상관관계가 아니다'에 대한 검증 용도의 p값이라고 봐야 하는 건가요? 아니면 어떻게 해석해야 하는 건가요?

**Comment by lovedlim** [comment]
stats.pearsonr(df['몸무게'], df['키']) 등과 같이 구할 때 
t검정에 대한 귀무가설은 "두 변수는 상관관계가 없다" 입니다. 알고 계신 지식이 맞습니다.
다만, 시험에서는 통계량 또는 p-value값을 반올림해서 입력하는 문제가 출제되고 있어요!

**Comment by routee90** [comment]
답변 감사합니다. 이제 봤네요.
