### ISSUE TITLE
정오표 추가할 내용 발견하여 글 올립니다.

### ISSUE THREAD

**Issue by routee90** [lovedlim/bigdata_analyst_cert#5]
안녕하세요

첫 발행이다 보니 오타가 너무 많아 보는데 신경이 곤두설 정도네요...
일단 다른 분들도 보셔야 되니 내용 공유합니다.

p421의 정확도 파트 from sklearn.metrics import accuracy_score 띄어쓰기 안되어있음
동일 페이지의 7번 문제 정답 1.4094682705862016로 보여지는데 1.2926...... 로 적혀있음. 확인 필요해 보임

또 보다가 문제 있으면 올려볼게요.

**Comment by lovedlim** [comment]
오타 제보 정말 감사합니다. 💪💪💪 해당 부분 정오표에 반영해 둘게요!
