### ISSUE TITLE
p187 문제 1번 정오표에 추가해주시면 좋을 듯합니다.

### ISSUE THREAD

**Issue by routee90** [lovedlim/bigdata_analyst_cert#6]
문제가 아니라 병합에 대한 조건이 적혀있네요..

**Comment by lovedlim** [comment]
(변경전)
1. school_data.csv와 school_data_science.csv의 학생 순서는 동일하다.

(변경후) 
1. 주어진 두 csv 파일(school_data.csv와 school_data_science.csv)을 학생 순서를 기준으로 병합하시오. (단, 두 파일의 학생 순서는 동일하다)

로 변경할게요! 피드백 너무 감사드립니다. 🙇🏻‍♂️
