### ISSUE TITLE
p199 4번 데이터 전처리의 (2) 이상치 아래 한계와 상위 한계의 괄호 안의 값이 동일하게 적혀있네요.

### ISSUE THREAD

**Issue by routee90** [lovedlim/bigdata_analyst_cert#7]
정오표 추가 부탁드립니다.

**Comment by lovedlim** [comment]
(변경전)
아래 한계(Q1 - 1.5 x IQR)
상위 한계(Q1 - 1.5 x IQR)

(변경후)
**하위** 한계(Q1 - 1.5 x IQR)
상위 한계(**Q3 +** 1.5 x IQR)
로 변경할게요! 감사합니다.
