### ISSUE TITLE
p419~421 로지스틱 회귀 문제 관련 질문드립니다.

### ISSUE THREAD

**Issue by YeEun8** [lovedlim/bigdata_analyst_cert#8]
책의 내용과 깃헙 코드 내용이 다른 것같은데
깃헙코드 내용이 맞는거죠 ?

**Comment by lovedlim** [comment]
코드 만큼은 틀리지 않으려고 했는데
도서 p.419~421부분은 잘못된 부분이 있어요!

이 영상 통해서 학습 부탁드립니다. (일부 변경)
https://youtu.be/zaDxb7Q9BdM?si=3a_Z7zTM8npO01OT

정오표
https://bit.ly/3YahBcW
