### ISSUE TITLE
p282 ~ 이진 분류 예측 질문드립니다

### ISSUE THREAD

**Issue by YeEun8** [lovedlim/bigdata_analyst_cert#9]
신용카드 신청자의 미래 신용 예측문제입니다.
baseline모델을 만들고, 2 ~ 4 번 모델은 parameter를 바꿔가면서 해보았는데요, 
3번 제외하고 predict label이 똑같이 예측되면서 f1 score도 동일하게 계산됩니다.
모델에 parameter tuning이 적용되지 않아 계속 동일한 모델이 만들어지는 것처럼 보이는데
제가 스크립트 상에 놓친 부분이 있을까요 ?.. 이런식으로 성능개선 테스트하면 안되는걸까요 ?!

![image](https://github.com/user-attachments/assets/7b1d1091-71fa-4e8c-8e66-b120c032f43e)
![image](https://github.com/user-attachments/assets/d63a6cb5-0207-4eae-9052-747799c59c50)

**Comment by lovedlim** [comment]
- 코드는 큰 문제 없어 보입니다. 이럴 경우 AI 답변(bot) 중 3번 처럼 다른 모델을 사용해보면 어떨까요 lightgbm 등 
- 아무래도 타겟이 불균형이 심한 데이터다 보니 성능이 올라가기 어려운 것 같아요.
